apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hcl
  template:
    metadata:
      labels:
        app: hcl
    spec:
      containers:
        - name: order-service
          image: public.ecr.aws/q4i7r7f2/hcl:BUILD_NUMBER
          ports:
            - containerPort: 3000
